[package]
name = "crony"
version = "0.1.0"
authors = ["Tibor Hudik <tibor@barrage.net>"]
edition = "2018"
license = "MIT"
keywords = ["cron", "runner"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cron = "0.7.0"
chrono = "0.4"
