name: Deploy

on:
  push:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  deploy:

    needs: test

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to Crates.io
      run: |
        cargo login $CRATES_IO_TOKEN
        cargo publish --verbose

