name: Deploy

on:
  push:
    branches: [ master ]
  merge: 
    branches: [ master ] 

env:
  CARGO_TERM_COLOR: always

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to Crates.io
      run: cargo login $CRATES_IO_TOKEN
    - name: Run publish
      run: cargo publish --verbose

